### ISSUE TITLE
FTA-FMEA Dashboard fails to load all elements due to a server side error.

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#122]
Investigate the server side error occurring during loading of dashboard elements in the `fta-fmea-demo` deployment.

**Comment by kostobog** [comment]
This issue is rather strange.

The Log in tomcat where the application is deployed is not updated and it does not contain error messages.

I tested it locally. When loading `faultTrees` the application throws a `NoHttpResponseException` exception, see  the exception log below. 

The exception is thrown in around 20 seconds after the request is sent. 

I checked the timeout configuration of the RDF server, repository and the apache proxy:
* global transaction timeout of the RDF server is `rdf4j.server.txn.registry.timeout = 0`
* configuration of the RDF repository `Query time-out (seconds) = 0` 
* in apache the graphdb location does not have a specified timeout, so I guess it uses the default one (300 seconds?)

The exception is not thrown consistently.

```
24-10-2023 15:02:51.656 [] [thread] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is cz.cvut.kbss.analysis.exception.PersistenceException: cz.cvut.kbss.jopa.exceptions.StorageAccessException: cz.cvut.kbss.ontodriver.sesame.exceptions.SesameDriverException: org.eclipse.rdf4j.repository.RepositoryException: org.apache.http.NoHttpResponseException: The target server failed to respond] with root cause 
org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1026)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:990)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendGraphQueryViaHttp(SPARQLProtocolSession.java:906)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getRDF(SPARQLProtocolSession.java:863)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.getStatements(RDF4JProtocolSession.java:599)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.exportStatements(HTTPRepositoryConnection.java:281)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.getStatements(HTTPRepositoryConnection.java:268)
	at cz.cvut.kbss.ontodriver.sesame.connector.PoolingStorageConnector.findStatements(PoolingStorageConnector.java:179)
	at cz.cvut.kbss.ontodriver.sesame.StatementLoader.loadOneByOne(StatementLoader.java:77)
	at cz.cvut.kbss.ontodriver.sesame.StatementLoader.loadAxioms(StatementLoader.java:64)
	at cz.cvut.kbss.ontodriver.sesame.AxiomLoader.findStatements(AxiomLoader.java:65)
	at cz.cvut.kbss.ontodriver.sesame.AxiomLoader.loadAxioms(AxiomLoader.java:53)
	at cz.cvut.kbss.ontodriver.sesame.SesameAdapter.find(SesameAdapter.java:178)
	at cz.cvut.kbss.ontodriver.sesame.SesameConnection.find(SesameConnection.java:175)
	at cz.cvut.kbss.jopa.oom.EntityInstanceLoader.loadInstance(EntityInstanceLoader.java:89)
	at cz.cvut.kbss.jopa.oom.DefaultInstanceLoader.loadEntity(DefaultInstanceLoader.java:32)
	at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.loadEntityInternal(ObjectOntologyMapperImpl.java:116)
	at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.loadEntity(ObjectOntologyMapperImpl.java:107)
	at cz.cvut.kbss.jopa.sessions.ConnectionWrapper.find(ConnectionWrapper.java:54)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.readObjectInternal(UnitOfWorkImpl.java:151)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.readObject(UnitOfWorkImpl.java:140)
	at cz.cvut.kbss.jopa.model.TypedQueryImpl.loadEntityInstance(TypedQueryImpl.java:95)
	at cz.cvut.kbss.jopa.model.TypedQueryImpl.lambda$getResultListImpl$0(TypedQueryImpl.java:80)
	at cz.cvut.kbss.jopa.model.AbstractQuery.executeQuery(AbstractQuery.java:290)
	at cz.cvut.kbss.jopa.model.TypedQueryImpl.getResultListImpl(TypedQueryImpl.java:78)
	at cz.cvut.kbss.jopa.model.TypedQueryImpl.getResultList(TypedQueryImpl.java:64)
	at com.github.ledsoft.jopa.spring.transaction.EntityManagerClosingTypedQueryProxy.getResultList(EntityManagerClosingTypedQueryProxy.java:35)
	at cz.cvut.kbss.analysis.dao.BaseDao.findAll(BaseDao.java:40)
	at cz.cvut.kbss.analysis.dao.BaseDao$$FastClassBySpringCGLIB$$8635a3c5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at cz.cvut.kbss.analysis.dao.FaultTreeDao$$EnhancerBySpringCGLIB$$bebf3f36.findAll(<generated>)
	at cz.cvut.kbss.analysis.service.BaseRepositoryService.findAll(BaseRepositoryService.java:66)
	at cz.cvut.kbss.analysis.service.BaseRepositoryService$$FastClassBySpringCGLIB$$f1fcbde1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at cz.cvut.kbss.analysis.service.FaultTreeRepositoryService$$EnhancerBySpringCGLIB$$cd032a0d.findAll(<generated>)
	at cz.cvut.kbss.analysis.controller.FaultTreeController.findAll(FaultTreeController.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by blcham** [comment]
I suggest to test it locally with:
- same data
- new graphdb

**Comment by blcham** [comment]
@kostobog  describe workaround and what do you think would be systematic solution

**Comment by blcham** [comment]
@kostobog 

- deploy new version to kbss with upgraded JOPA v0.22.2 and test if it works correctly

**Comment by blcham** [comment]
Upgrade to new JOPA solved the issues (see PRs on the fta-fmea backend).
