### ISSUE TITLE
FTA-FMEA-UI dashboard fails to load properly

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#125]
The UI throws exception:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at ./src/services/utils/uriIdentifierUtils.tsx.exports.extractFragment (uriIdentifierUtils.tsx:5:1)
    at DashboardFailureModesTableList.tsx:38:1
    at Array.map (<anonymous>)
    at DashboardFailureModesTableList (DashboardFailureModesTableList.tsx:37:86)
    at renderWithHooks (react-dom.development.js:14803:1)
    at updateFunctionComponent (react-dom.development.js:17034:1)
    at beginWork (react-dom.development.js:18610:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
```

**Comment by blcham** [comment]
@kostobog i guess i can close this
