### ISSUE TITLE
Cannot create System/FTA tree

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#294]
When I try to create System/FTA tree get HTTP response error 500 from backend:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/31b9bfe0-3377-4919-8a1f-d9b4f748666b)

The backend logs following error:
```
ff-kauth-demo-fta-fmea-server  | 17-05-2024 11:31:38.252 [] [thread] ERROR c.c.k.j.d.util.ClasspathScanner - Unable to scan classes in JAR file nested:/fta-fmea.jar/!BOOT-INF/classes/!/cz/cvut/kbss/analysis
ff-kauth-demo-fta-fmea-server  | java.nio.file.NoSuchFileException: nested:/fta-fmea.jar/!BOOT-INF/classes/!/cz/cvut/kbss/analysis
ff-kauth-demo-fta-fmea-server  |        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
ff-kauth-demo-fta-fmea-server  |        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
ff-kauth-demo-fta-fmea-server  |        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
ff-kauth-demo-fta-fmea-server  |        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
ff-kauth-demo-fta-fmea-server  |        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
ff-kauth-demo-fta-fmea-server  |        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1428)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.util.jar.JarFile.<init>(JarFile.java:256)
ff-kauth-demo-fta-fmea-server  |        at cz.cvut.kbss.jsonld.deserialization.util.ClasspathScanner.processJarFile(ClasspathScanner.java:107)
ff-kauth-demo-fta-fmea-server  |        at cz.cvut.kbss.jsonld.deserialization.util.ClasspathScanner.processClasses(ClasspathScanner.java:72)
ff-kauth-demo-fta-fmea-server  |        at cz.cvut.kbss.jsonld.deserialization.JsonLdDeserializer.initializeTargetClassResolver(JsonLdDeserializer.java:59)
ff-kauth-demo-fta-fmea-server  |        at cz.cvut.kbss.jsonld.deserialization.JsonLdDeserializer.<init>(JsonLdDeserializer.java:48)
ff-kauth-demo-fta-fmea-server  |        at cz.cvut.kbss.jsonld.deserialization.expanded.ExpandedJsonLdDeserializer.<init>(ExpandedJsonLdDeserializer.java:34)
ff-kauth-demo-fta-fmea-server  |        at cz.cvut.kbss.jsonld.deserialization.JsonLdDeserializer.createExpandedDeserializer(JsonLdDeserializer.java:104)
ff-kauth-demo-fta-fmea-server  |        at cz.cvut.kbss.jsonld.jackson.deserialization.JacksonJsonLdDeserializer.deserialize(JacksonJsonLdDeserializer.java:66)
ff-kauth-demo-fta-fmea-server  |        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
ff-kauth-demo-fta-fmea-server  |        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
ff-kauth-demo-fta-fmea-server  |        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
ff-kauth-demo-fta-fmea-server  |        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395)


....


ff-kauth-demo-fta-fmea-server  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
ff-kauth-demo-fta-fmea-server  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
ff-kauth-demo-fta-fmea-server  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ff-kauth-demo-fta-fmea-server  |        at java.base/java.lang.Thread.run(Thread.java:840)
ff-kauth-demo-fta-fmea-server  | 17-05-2024 11:31:38.373 [] [thread] INFO  c.c.k.a.controller.SystemController - > create - System <null/>
ff-kauth-demo-fta-fmea-server  | 17-05-2024 11:31:38.463 [] [thread] WARN  c.c.k.a.c.util.RestExceptionHandler - > handleNotFoundError - /fta-fmea/systems
```

[Uploading complete.log.txt…]()

**Comment by blcham** [comment]
I tried 3 different images where it behaves the same in `deploy/keycloak-auth/docker-compose.yml`:
- local docker image from main (7a7ba9c6af0aa2a89259747ac969c2fca88a93ec)
  - image: fta-fmea-local:latest
- public docker image from main 
  - image: ghcr.io/kbss-cvut/fta-fmea:latest
- public image from pulls/95:    
   - image: ghcr.io/kbss-cvut/fta-fmea:pr-95

**Comment by blcham** [comment]
The issue does not manifest in `deploy/internal-auth`

**Comment by ledsoft** [comment]
@kostobog @blcham Update JB4JSON-LD to the latest version, the issue was caused by changes in Spring Boot archive structure in 3.2.x, see https://github.com/kbss-cvut/jb4jsonld/releases/tag/v0.14.2

**Comment by LaChope** [comment]
I hope that https://github.com/kbss-cvut/fta-fmea-ui/pull/293 will resolve it.

**Comment by blcham** [comment]
As @ledsoft suggested, https://github.com/kbss-cvut/fta-fmea/pull/98 resolved issues with most of the errors above. The only remaining issue is the following:
```
ff-kauth-demo-fta-fmea-server  | 17-05-2024 11:31:38.373 [] [thread] INFO  c.c.k.a.controller.SystemController - > create - System <null/>
ff-kauth-demo-fta-fmea-server  | 17-05-2024 11:31:38.463 [] [thread] WARN  c.c.k.a.c.util.RestExceptionHandler - > handleNotFoundError - /fta-fmea/systems
```

**Comment by kostobog** [comment]
@blcham 
I think the problem occurs when fetching the current user with ( to be set as the creator of the system or fault tree) see `ComplexManagedEntityRepositoryService.prePersist`. 

Eventually the `UserDao.findByUsername` is called which uses incompatible username and password properties. 

**Other** 
Also I see that the user saved in the default context has language tags for username and password. FTA FMEA has this properties as simple literals with no language tags.
