### ISSUE TITLE
Fix fault tree editor does not work as expected after failure rate is updated

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#533]
Fault tree editor does not work as expected after opening a fault tree which is has operational failure rate calculated during evaluation of fault tree.

![Image](https://github.com/user-attachments/assets/f716337c-1e77-488a-b78f-6624e72b6dcd)

**Comment by kostobog** [comment]
Error in browser console:
```
Uncaught (in promise) TypeError: a.supertypes.supertypes.reduce is not a function
    at renderTree (RenderTree.tsx:61:76)
    at RenderTree.tsx:119:45
    at Array.map (<anonymous>)
    at renderTree (RenderTree.tsx:119:34)
    at EditorCanvas.tsx:267:15
    at EditorCanvas.tsx:270:7
    at Rj (react-dom.production.min.js:244:332)
    at Ik (react-dom.production.min.js:286:111)
    at Fk (react-dom.production.min.js:273:185)
    at jg (react-dom.production.min.js:127:105)
```



![Image](https://github.com/user-attachments/assets/1f5ce026-69c7-4c53-a4c9-65b462cd83bf)
