### ISSUE TITLE
Check the aero-vodochody deployment features latest fta-fmea version

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#98]
There is a problem with the [FTA/FMEA tool deployment for Aero Vodochody](http://kbss.felk.cvut.cz/fta-fmea-aero-vodochody). 
When editing component, I cannot add a function and failure mode does not have the field "failure mode type".

![image](https://user-images.githubusercontent.com/18463762/192491002-05f225aa-57ee-4d2d-94cc-961a2c5172ed.png)

**Comment by kostobog** [comment]
It seams that adding functions works fine. See image below where a new function was added.
![image](https://user-images.githubusercontent.com/18463762/192497117-c896ec7f-48d2-4e95-9ba8-beb99d987375.png)

**Comment by kostobog** [comment]
I checked the deployment. You were right an older version of the fta-fmea was deployed. I updated the current version in the avic branch and deployed it to the [fta fmea Aero Vodochody deployment](http://kbss.felk.cvut.cz/fta-fmea-aero-vodochody), see below for more technical details.
 
@lalisand can you check if the current deployment is correct.

### Technical Details
After updating the avic branch to the current version the server could not be deployed due to an error during deployment, see stack trace below. Shortly, there were multiple mappings for the register method. The error was resolved by removing the register method in the AuthController, see commit [Remove register method from the AuthController](https://github.com/kbss-cvut/fta-fmea/commit/6598ce580e2b771f82e1f2c348212bcc39da8c4f).

**Stack Trace**
```
27-Sep-2022 12:43:34.972 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
27-Sep-2022 12:43:37.895 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/fta-fmea-aero-vodochody-server]]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:441)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1858)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:772)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1629)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:304)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1176)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1398)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1402)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1370)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'authController' method
cz.cvut.kbss.analysis.controller.AuthController#register(User)
to {POST /auth/register, consumes [application/ld+json], produces [application/json]}: There is already 'adminRegistrationController' bean method
cz.cvut.kbss.analysis.controller.AdminRegistrationController#register(User) mapped.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:173)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:153)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:95)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5098)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        ... 19 more
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'authController' method
cz.cvut.kbss.analysis.controller.AuthController#register(User)
to {POST /auth/register, consumes [application/ld+json], produces [application/json]}: There is already 'adminRegistrationController' bean method
cz.cvut.kbss.analysis.controller.AdminRegistrationController#register(User) mapped.
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.validateMethodMapping(AbstractHandlerMethodMapping.java:636)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.register(AbstractHandlerMethodMapping.java:603)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.registerHandlerMethod(AbstractHandlerMethodMapping.java:318)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:378)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:75)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lambda$detectHandlerMethods$1(AbstractHandlerMethodMapping.java:288)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:286)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.processCandidateBean(AbstractHandlerMethodMapping.java:258)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:217)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:205)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:189)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
        ... 39 more

```

**Comment by lalisand** [comment]
> @lalisand It seams that adding functions works fine. See image below where a new function was added. ![image](https://user-images.githubusercontent.com/18463762/192497117-c896ec7f-48d2-4e95-9ba8-beb99d987375.png)

This one is not resolved. I underspecified the problem description, sorry for that. What I means is e.g. adding function to the "Hlavní okruh" aggregate. I would like to add required functions (random selection of functions of the subordiate component, like "Tlakový snímač", "Filtr", "Tlakový spínač" etc,), but after clicking the "+" button to create the function, I receive "Failed to create the function" message. It does not create it. The same problem exist when function parts are included. Functions can be saved only when atomic and independent of anything else.

See example function, that will fail to create:
![Functions](https://user-images.githubusercontent.com/94048408/192608911-c8516eec-e2a3-4a8a-8228-f8d8b82ec36f.png)

**Comment by kostobog** [comment]
@lalisand 
To answer the questions from the [post above](https://github.com/kbss-cvut/fta-fmea-ui/issues/98#issuecomment-1262313693) shortly :

1. What do you mean the same issue? Do you see an older version of the tool? 
    - If so clearing the cache should work. Also you can that there is an issue with older version cached in the browser if you open the deployment in incognito mode. 
    - If the version of the deployment is correct but there is a new issue please create a new issue here. 
2. So far the tool allows to detach and attach function to the component. Currently we do not have a method to delete the function from the database using the UI. If this is required I will create a ticket and we will find time to add this feature.
3. What is the difference between function part and required function?
    -  Examples 
        - A required function is a function that is required in order to perform the function that requires it. For example, a cooling sub-system might require electrical power to perform the cooling function. 
        - Function parts can be used to construct a function that is constituted by other functions. For example, a redundant power source provides power to an external system. The power provision function of the redundant power source is constituted by the power provision functions of the alternative power sources (e.g. main and back-up power sources) and a power source selection function. In this particular example the OR behavior type will be used to combine the function of the main and back-up power supplies. Note that in this case the other functions are not required but are constituent parts of the redundant power function. 
     - Example diagrams of how required functions and function parts are translated into FTA can be found [here](https://github.com/kbss-cvut/fta-fmea-ui/blob/main/doc/fta-construction-algorithm.md), see the diagrams.

**Comment by lalisand** [comment]
@kostobog thanks for this.
1. I see new version of the tool (MŠMT logo + InterExcellence) and FailureModeType. But the behavior is the same as in older version of the tool in terms of not allowing to create functions that have parts or required functions.
2. I see. Maybe if we could just delete some functions from the database (by asking you), the UI feature would not be necessary. anyway, Miro was asking me about FTA/FMEA tool UI development today, as one of his students could work on this. I think this would be a nice candidate for that.
3. I see, thanks for this.

**Comment by lalisand** [comment]
```
react-dom.development.js:24994 Download the React DevTools for a better development experience: https://fb.me/react-devtools
/fta-fmea-aero-vodochody-server/systems:1          Failed to load resource: the server responded with a status of 401 ()
axiosUtils.tsx:13 Axios response returned 401. Logging out...
systemService.tsx:29 System Service - Failed to call /findAll
/fta-fmea-aero-vodochody-server/faultTrees:1          Failed to load resource: the server responded with a status of 401 ()
axiosUtils.tsx:13 Axios response returned 401. Logging out...
faultTreeService.tsx:30 Fault Tree Service - Failed to call /findAll
/fta-fmea-aero-vodochody-server/failureModesTable:1          Failed to load resource: the server responded with a status of 401 ()
axiosUtils.tsx:13 Axios response returned 401. Logging out...
failureModesTableService.tsx:28 Failure Modes Table Service - Failed to call /findAll
/favicon.ico:1          Failed to load resource: the server responded with a status of 404 (Not Found)
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance239436323","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Hlavní okruh","linkedComponent":{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638"}}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Síť tlakového potrubí"}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Síť tlakového potrubí"}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Síť tlakového potrubí"}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
/fta-fmea-aero-vodochody-server/components/instance239436323/functions:1          Failed to load resource: the server responded with a status of 500 ()
componentService.tsx:120 Component Service - Failed to call create function
responseUtils.tsx:16 Response status - 500
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Síť tlakového potrubí"}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Síť tlakového potrubí"}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Síť tlakového potrubí"}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
useAutocomplete.js:249 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `{"iri":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component/instance533127638","types":"http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Component","failureModes":[],"functions":[],"name":"Síť tlakového potrubí"}`.
You can use the `getOptionSelected` prop to customize the equality test.
useAutocomplete @ useAutocomplete.js:249
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```

**Comment by kostobog** [comment]
@lalisand 
Issue with adding new functions with parts and or required functions is fixed

**Comment by lalisand** [comment]
@kostobog 
We have a new issue with the Aero vodochody deployment. After left-clicking any of the "Hlavní okruh" components (parts), the tool goes blank white. It is not possible to edit these components.
![FTA_FMEA_problem3](https://user-images.githubusercontent.com/94048408/193799729-afc6f064-59d9-46fb-8d79-b7fba2faf413.png)

**Comment by lalisand** [comment]
@kostobog 
We have now reported new set of issues from my students. I am sending first two issues:

1. The same problem re-emerged as above, i.e. function parts and required functions cannot be defined. But now the problem is only in case when functions of "hlavní okruh" or "nouzový okruh" components should be added as function parts or required functions to some other component. For example, if I select "Síť tlakového potrubí" and decide to edit function "111" by adding required function "Vedení hydraulické kapaliny" of the "Hlavní okruh" component, the FTA/FMEA tool fails to update the fuction.
![Function_parts](https://user-images.githubusercontent.com/94048408/194326866-a82bbd67-9ade-4312-87b1-9ea57b0cce15.png)

2. For some reason, it is impossible to add new Failure Mode to "Tlakový snímač N.O." component, when it is linked to "Nouzový okruh" component (with part-of). As soon as the part-of relation is removed, new FM can be added.
![NO_component](https://user-images.githubusercontent.com/94048408/194332099-0fc5b512-8750-417b-a498-cfbed2567230.png)

**Comment by lalisand** [comment]
@kostobog

Here is a description of problem 3:

FTA/FMEA tool seems to not update FTA trees after functions/failure modes update. Whatever the first tree is, it will not update when components/functions/failure modes are updated. Example is "Hlavní okruh", where I dropped/added many failure modes of the part-of components to "Hlavní okruh", but the tree generated remains the same.

![Hlavni_okruh](https://user-images.githubusercontent.com/94048408/194398616-8526eaf2-ccc6-4a8b-a131-9076867f1b14.png)

**Comment by kostobog** [comment]
@lalisand @Matthew-Kulich 
I pushed and deployed the new version.

**Comment by Matthew-Kulich** [comment]
@kostobog 
Issue: 
Cannot update behavior type in FailureMode `Cerpadlo` (MK-test system-> Hlavni okruh-> FailureModes [link](https://kbss.felk.cvut.cz/fta-fmea-aero-vodochody/#/system/instance-985442219))
But it is weird because there are already assigned parts.

**Comment by Matthew-Kulich** [comment]
@lalisand Yeah, I will help with that
